### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by sonovice** [compiteing/ponywhoosh#1]
Hi!
Are there any plans on supporting Python 3 in the future?

**Comment by piperod** [comment]
Yes, we will work on that this summer.

El may. 17, 2017 6:07 AM, Simon Waloschek <notifications@github.com> escribió:

Hi!
Are there any plans on supporting Python 3 in the future?

**Comment by jonaprieto** [comment]
Any news about this (?)

**Comment by jonaprieto** [comment]
Please check the new support.
