### ISSUE TITLE
No results, index not created, and problem with primary key

### ISSUE THREAD

**Issue by masfaraud** [compiteing/ponywhoosh#4]
I use ponywhoosh as specified:
```
@pw.register_model('name', sortable=True, stored=True)
class Product(pony_db.Entity):
   name = pony.orm.Required(str, 200, unique=True)
```

```
@app.route('/search', methods=['GET'])
@limiter.limit("1000/day")
@pony.orm.db_session
def search():
    query = request.args.get('query', type=str)
    print('query', query)
    return json.dumps(models.pw.search(query))
```

Searching show no results with a populated database and exact query.
By looking into the index folder, I realized that indexes were not built. So I tried the following:

```
Product._pw_index_.update_documents()
```
I get this error:
```
  File "/usr/local/lib/python3.6/dist-packages/ponywhoosh/index.py", line 136, in charge_documents
    attrs = {self._primary_key: obj.get_pk()}

TypeError: unhashable type: 'list'
```

Do you have any clue?

**Comment by piperod** [comment]
Did you populate the database after registering the class or the database was populated already?

**Comment by masfaraud** [comment]
The database was already populated.

**Comment by piperod** [comment]
I think this is a whoosh related issue, where you may need to repopulate the database so the indexes are created.

**Comment by masfaraud** [comment]
Ok, thanks
